# Header
fa_logo: fa-cube

# Header
menu:
  首页: /
  归档: /archives
  关于: /about.html
  标签: /tags
  分类: /categories
  联系: /contact.html

# Default post title
default_post_title: 无标题

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-alpha-dust
telegram_url: https://telegram.org/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: test@example.com
rss_url: \#

# Footer About Text
footer_about: "这个主题由 <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a> 开发。源代码可在 Github 上获取。创建网站，创造魔法。"

# Footer Copyright Line
footer_copyright: "@无标题. 保留所有权利 | 设计 & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
